version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=sqlite:///instance/mercatorio.db
      - UPLOAD_FOLDER=/app/uploads
      - MAX_CONTENT_LENGTH=10485760  # 10MB em bytes
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mercatorio
      - POSTGRES_PASSWORD=mercatorio_password
      - POSTGRES_DB=mercatorio
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data:
